import spotipy
from spotipy.oauth2 import SpotifyOAuth

scope = ["user-library-read", "playlist-read-private","playlist-modify-public", "playlist-modify-private"]

playlist_ids = ["5S3d59oNAopZwtAgYjuQRm", "2iiWuUtPgGFsGdM6B7kGA4", "3g0vH1gBDliXwMH18Lhs7t"]

def fetch_all_playlists_from_user(spotify_client : spotipy.Spotify):
    playlists = spotify_client.current_user_playlists()

    for playlist in playlists['items']:
        
        id = playlist['id']
        playlist_name = playlist['name']

        if id not in playlist_ids:
            continue

        print(f"---------------------------------------------- Playlist name = {playlist_name} ----------------------------------------------")
        tracks = spotify_client.playlist_tracks(playlist_id= id)
        my_playlist = []

        for track in tracks['items']:
            track_id = track['track']['id']
            audio_analysis = spotify_client.audio_analysis(track_id=track_id)
            my_track = {}
            my_track['name'] = track['track']['name']
            my_track['uri'] = track['track']['uri']
            my_track['bpm'] = audio_analysis['track']['tempo']
            my_track['key'] = audio_analysis['track']['key']
            my_playlist.append(my_track)

        my_playlist.sort(key= lambda x: x['bpm'], reverse=False)
        create_new_playlist(spotify_client, my_playlist, playlist_name)
        


def create_new_playlist(spotify_client : spotipy.Spotify, my_playlist : list, playlist_name : str):
    user_id = spotify_client.current_user()['id']
    playlist_new_name = playlist_name + "(Generated by AI)"
    new_playlist = spotify_client.user_playlist_create(user= user_id, name=playlist_new_name, public=False, collaborative=False)
    new_playlist_id = new_playlist['id']
    
    for track in my_playlist:
        print(track)
        spotify_client.user_playlist_add_tracks(user=user_id, playlist_id=new_playlist_id, tracks=[track['uri']])
    

    

def login_user():
    sp = spotipy.Spotify(auth_manager=SpotifyOAuth(scope=scope))
    return sp
    

if __name__ == "__main__":
    spotify_client = login_user()
    fetch_all_playlists_from_user(spotify_client)


